/**
 * config.js — scrape targets for run.js
 * ---------------------------------------------------------------------------
 * Generated from the verified-leads sheet (123 companies).
 *
 * `method` is null on every entry. It cannot be known without fetching each
 * careers page, and a guessed adapter is worse than no adapter — it produces
 * silent zero-result runs that look like "no openings". Run:
 *
 *     node scripts/detect-ats.js
 *
 * which probes each careers URL and writes `method` and `atsSlug` back into
 * this file, printing the ones it could not resolve.
 *
 * Until a company has a method, run.js skips it and logs it as skipped rather
 * than failed. That is why the board shows no live roles on a fresh install:
 * nothing is scrapeable yet.
 *
 * To set one by hand, find the company below and fill in both fields:
 *     method: "greenhouse",   atsSlug: "their-board-token"
 */

export const COMPANIES = [
  {
    id: "appfolio",
    name: "AppFolio",
    hub: "proptech",
    careersUrl: "https://www.appfolio.com/company/careers",
    website: "https://www.appfolio.com",
    state: "California",
    segment: "Property Management Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "yardi-systems",
    name: "Yardi Systems",
    hub: "proptech",
    careersUrl: "https://www.yardi.com/careers",
    website: "https://www.yardi.com",
    state: "California",
    segment: "Property Management Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "procore-technologies",
    name: "Procore Technologies",
    hub: "proptech",
    careersUrl: "https://www.procore.com/careers",
    website: "https://www.procore.com",
    state: "California",
    segment: "Construction Tech",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "matterport",
    name: "Matterport",
    hub: "proptech",
    careersUrl: "https://matterport.com/careers",
    website: "https://matterport.com",
    state: "California",
    segment: "3D Space Capture / Real Estate Media",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "measurabl",
    name: "Measurabl",
    hub: "proptech",
    careersUrl: "https://measurabl.com/careers",
    website: "https://measurabl.com",
    state: "California",
    segment: "ESG/Sustainability Data for CRE",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "placerai",
    name: "Placer.ai",
    hub: "proptech",
    careersUrl: "https://www.placer.ai/careers",
    website: "https://www.placer.ai",
    state: "California",
    segment: "Foot Traffic / Location Analytics",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "roofstock",
    name: "Roofstock",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.roofstock.com/careers",
    website: "https://www.roofstock.com",
    state: "California",
    segment: "SFR Investment Marketplace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "mynd",
    name: "Mynd",
    hub: "opco",
    careersUrl: "https://www.mynd.co/careers",
    website: "https://www.mynd.co",
    state: "California",
    segment: "SFR Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "doma",
    name: "Doma",
    hub: "proptech",
    careersUrl: "https://www.doma.com/careers",
    website: "https://www.doma.com",
    state: "California",
    segment: "Title Insurance / Mortgage Tech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "blend-labs",
    name: "Blend Labs",
    hub: "proptech",
    careersUrl: "https://blend.com/careers",
    website: "https://www.blend.com",
    state: "California",
    segment: "Mortgage/Lending Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "point",
    name: "Point",
    hub: "proptech",
    careersUrl: "https://www.point.com/careers",
    website: "https://www.point.com",
    state: "California",
    segment: "Home Equity Fintech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "divvy-homes",
    name: "Divvy Homes",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.divvyhomes.com/careers",
    website: "https://www.divvyhomes.com",
    state: "California",
    segment: "Rent-to-Own Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "flock-homes",
    name: "Flock Homes",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.flockhomes.com/careers",
    website: "https://www.flockhomes.com",
    state: "California",
    segment: "SFR 1031 Exchange Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "zumper",
    name: "Zumper",
    hub: "proptech",
    careersUrl: "https://www.zumper.com/careers",
    website: "https://www.zumper.com",
    state: "California",
    segment: "Rental Marketplace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "apartment-list",
    name: "Apartment List",
    hub: "proptech",
    careersUrl: "https://www.apartmentlist.com/careers",
    website: "https://www.apartmentlist.com",
    state: "California",
    segment: "Rental Marketplace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "hemlane",
    name: "Hemlane",
    hub: "proptech",
    careersUrl: "https://www.hemlane.com/careers",
    website: "https://www.hemlane.com",
    state: "California",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "pacaso",
    name: "Pacaso",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.pacaso.com/careers",
    website: "https://www.pacaso.com",
    state: "California",
    segment: "Co-Ownership / Second Homes",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "crexi",
    name: "Crexi",
    hub: "proptech",
    careersUrl: "https://www.crexi.com/careers",
    website: "https://www.crexi.com",
    state: "California",
    segment: "CRE Marketplace & Data",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "kiavi",
    name: "Kiavi",
    hub: "proptech",
    careersUrl: "https://www.kiavi.com/careers",
    website: "https://www.kiavi.com",
    state: "California",
    segment: "Real Estate Investor Lending",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "kasa-living",
    name: "Kasa Living",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.kasa.com/careers",
    website: "https://www.kasa.com",
    state: "California",
    segment: "Flexible-Stay Hospitality Tech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "side",
    name: "Side",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.side.com/careers",
    website: "https://www.side.com",
    state: "California",
    segment: "Real Estate Brokerage Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "housecanary",
    name: "HouseCanary",
    hub: "proptech",
    careersUrl: "https://www.housecanary.com/careers",
    website: "https://www.housecanary.com",
    state: "California",
    segment: "Real Estate Valuation/AVM Data",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "homelight",
    name: "HomeLight",
    hub: "proptech",
    careersUrl: "https://www.homelight.com/careers",
    website: "https://www.homelight.com",
    state: "California",
    segment: "Agent Matching / Real Estate Marketplace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "snapdocs",
    name: "Snapdocs",
    hub: "proptech",
    careersUrl: "https://www.snapdocs.com/careers",
    website: "https://www.snapdocs.com",
    state: "California",
    segment: "Digital Mortgage Closing Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "rentspree",
    name: "RentSpree",
    hub: "proptech",
    careersUrl: "https://www.rentspree.com/careers",
    website: "https://www.rentspree.com",
    state: "California",
    segment: "Tenant Screening Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "realtorcom-move-inc",
    name: "Realtor.com (Move Inc.)",
    hub: "proptech",
    careersUrl: "https://www.move.com/careers",
    website: "https://www.realtor.com",
    state: "California",
    segment: "Real Estate Listings Marketplace",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "auctioncom",
    name: "Auction.com",
    hub: "proptech",
    careersUrl: "https://www.auction.com/careers",
    website: "https://www.auction.com",
    state: "California",
    segment: "Real Estate Auction Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "realpage",
    name: "RealPage",
    hub: "proptech",
    careersUrl: "https://www.realpage.com/careers",
    website: "https://www.realpage.com",
    state: "Texas",
    segment: "Property Management Data & Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "resman",
    name: "ResMan",
    hub: "proptech",
    careersUrl: "https://myresman.com/careers",
    website: "https://myresman.com",
    state: "Texas",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "homeward",
    name: "Homeward",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.homeward.com/careers",
    website: "https://www.homeward.com",
    state: "Texas",
    segment: "Cash-Offer / Mortgage Fintech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "steadily",
    name: "Steadily",
    hub: "proptech",
    careersUrl: "https://www.steadily.com/careers",
    website: "https://www.steadily.com",
    state: "Texas",
    segment: "Landlord Insurance",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "closinglock",
    name: "Closinglock",
    hub: "proptech",
    careersUrl: "https://www.closinglock.com/careers",
    website: "https://www.closinglock.com",
    state: "Texas",
    segment: "Wire Fraud Prevention for RE Closings",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "certifid",
    name: "CertifID",
    hub: "proptech",
    careersUrl: "https://www.certifid.com/careers",
    website: "https://www.certifid.com",
    state: "Texas",
    segment: "Wire Fraud Prevention / Identity Verification",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "luxury-presence",
    name: "Luxury Presence",
    hub: "proptech",
    careersUrl: "https://www.luxurypresence.com/careers",
    website: "https://www.luxurypresence.com",
    state: "Texas",
    segment: "Real Estate Agent Marketing Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "greenlite",
    name: "GreenLite",
    hub: "proptech",
    careersUrl: "https://www.greenlite.ai/careers",
    website: "https://www.greenlite.ai",
    state: "Texas",
    segment: "AI Permitting & Compliance",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "worksmith",
    name: "Worksmith",
    hub: "proptech",
    careersUrl: "https://www.worksmith.com/careers",
    website: "https://www.worksmith.com",
    state: "Texas",
    segment: "Retail/CRE Facilities Marketplace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "ownwell",
    name: "Ownwell",
    hub: "proptech",
    careersUrl: "https://www.ownwell.com/careers",
    website: "https://www.ownwell.com",
    state: "Texas",
    segment: "Property Tax Appeal Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "ojo-labs",
    name: "Ojo Labs",
    hub: "proptech",
    careersUrl: "https://www.ojolabs.com/careers",
    website: "https://www.ojolabs.com",
    state: "Texas",
    segment: "AI Real Estate Assistant",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "opcity-realtorcom",
    name: "Opcity (Realtor.com)",
    hub: "proptech",
    careersUrl: "https://www.move.com/careers",
    website: "https://www.opcity.com",
    state: "Texas",
    segment: "Real Estate Lead Conversion Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "compass",
    name: "Compass",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.compass.com/careers",
    website: "https://www.compass.com",
    state: "New York",
    segment: "Real Estate Brokerage Tech",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "vts",
    name: "VTS",
    hub: "proptech",
    careersUrl: "https://www.vts.com/careers",
    website: "https://www.vts.com",
    state: "New York",
    segment: "Commercial Real Estate Leasing Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "butterflymx",
    name: "ButterflyMX",
    hub: "proptech",
    careersUrl: "https://www.butterflymx.com/careers",
    website: "https://www.butterflymx.com",
    state: "New York",
    segment: "Smart Access / Intercom Systems",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "guesty",
    name: "Guesty",
    hub: "proptech",
    careersUrl: "https://www.guesty.com/careers",
    website: "https://www.guesty.com",
    state: "New York",
    segment: "Short-Term Rental Management Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "rhino",
    name: "Rhino",
    hub: "proptech",
    careersUrl: "https://www.sayrhino.com/careers",
    website: "https://www.sayrhino.com",
    state: "New York",
    segment: "Security Deposit Insurance",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "bilt-rewards",
    name: "Bilt Rewards",
    hub: "proptech",
    careersUrl: "https://www.biltrewards.com/careers",
    website: "https://www.biltrewards.com",
    state: "New York",
    segment: "Rent Rewards / Resident Fintech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "compstak",
    name: "CompStak",
    hub: "proptech",
    careersUrl: "https://www.compstak.com/careers",
    website: "https://www.compstak.com",
    state: "New York",
    segment: "CRE Comparable Data Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "cadre",
    name: "Cadre",
    hub: "proptech",
    careersUrl: "https://www.cadre.com/careers",
    website: "https://www.cadre.com",
    state: "New York",
    segment: "CRE Investment Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "squarefoot",
    name: "SquareFoot",
    hub: "proptech",
    careersUrl: "https://www.squarefoot.com/careers",
    website: "https://www.squarefootfinance.com",
    state: "New York",
    segment: "Commercial Office Brokerage Tech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "latch",
    name: "Latch",
    hub: "proptech",
    careersUrl: "https://www.latch.com/careers",
    website: "https://www.latch.com",
    state: "New York",
    segment: "Smart Access for Multifamily",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "agora",
    name: "Agora",
    hub: "proptech",
    careersUrl: "https://www.agora-re.com/careers",
    website: "https://www.agora-re.com",
    state: "New York",
    segment: "Real Estate Investment Management SaaS/Fintech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "cherre",
    name: "Cherre",
    hub: "proptech",
    careersUrl: "https://www.cherre.com/careers",
    website: "https://www.cherre.com",
    state: "New York",
    segment: "Real Estate Data Integration Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "enertiv",
    name: "Enertiv",
    hub: "proptech",
    careersUrl: "https://www.enertiv.com/careers",
    website: "https://www.enertiv.com",
    state: "New York",
    segment: "Building Energy Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "bowery-valuation",
    name: "Bowery Valuation",
    hub: "proptech",
    careersUrl: "https://www.boweryvaluation.com/careers",
    website: "https://www.boweryvaluation.com",
    state: "New York",
    segment: "AI-Powered Appraisal Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "obligo",
    name: "Obligo",
    hub: "proptech",
    careersUrl: "https://www.myobligo.com/careers",
    website: "https://www.myobligo.com",
    state: "New York",
    segment: "Security Deposit Alternative",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "theguarantors",
    name: "TheGuarantors",
    hub: "proptech",
    careersUrl: "https://www.theguarantors.com/careers",
    website: "https://www.theguarantors.com",
    state: "New York",
    segment: "Lease Insurance / Insurtech",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "funnel-leasing",
    name: "Funnel Leasing",
    hub: "proptech",
    careersUrl: "https://www.funnelleasing.com/careers",
    website: "https://www.funnelleasing.com",
    state: "New York",
    segment: "Multifamily Leasing CRM",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "wework",
    name: "WeWork",
    hub: "opco",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.wework.com/careers",
    website: "https://www.wework.com",
    state: "New York",
    segment: "Flexible Workspace",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "industrious",
    name: "Industrious",
    hub: "opco",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.industriousoffice.com/careers",
    website: "https://www.industriousoffice.com",
    state: "New York",
    segment: "Flexible Workspace",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "convene",
    name: "Convene",
    hub: "opco",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://convene.com/careers",
    website: "https://convene.com",
    state: "New York",
    segment: "Flexible Workspace / Meeting Venues",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "orchard",
    name: "Orchard",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.orchard.com/careers",
    website: "https://www.orchard.com",
    state: "New York",
    segment: "Home Trade-In / Mortgage Fintech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "bettercom",
    name: "Better.com",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://better.com/careers",
    website: "https://better.com",
    state: "New York",
    segment: "Digital Mortgage Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "updater",
    name: "Updater",
    hub: "proptech",
    careersUrl: "https://www.updater.com/careers",
    website: "https://www.updater.com",
    state: "New York",
    segment: "Moving/Relocation Tech for Property Managers",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "livly",
    name: "Livly",
    hub: "proptech",
    careersUrl: "https://www.livly.io/careers",
    website: "https://www.livly.io",
    state: "Illinois",
    segment: "Resident Experience Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "chamberlain-group",
    name: "Chamberlain Group",
    hub: "proptech",
    careersUrl: "https://www.chamberlaingroup.com/careers",
    website: "https://www.chamberlaingroup.com",
    state: "Illinois",
    segment: "Smart Access (myQ/LiftMaster)",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "obie",
    name: "Obie",
    hub: "proptech",
    careersUrl: "https://www.obieinsurance.com/careers",
    website: "https://www.obieinsurance.com",
    state: "Illinois",
    segment: "Landlord Insurance / Insurtech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "avail-realtorcom",
    name: "Avail (Realtor.com)",
    hub: "proptech",
    careersUrl: "https://www.avail.co/careers",
    website: "https://www.avail.co",
    state: "Illinois",
    segment: "DIY Landlord Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "hqo",
    name: "HqO",
    hub: "proptech",
    careersUrl: "https://www.hqo.com/careers",
    website: "https://www.hqo.com",
    state: "Massachusetts",
    segment: "Tenant/Workplace Experience Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "buildium-realpage",
    name: "Buildium (RealPage)",
    hub: "proptech",
    careersUrl: "https://www.buildium.com/careers",
    website: "https://www.buildium.com",
    state: "Massachusetts",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "placester",
    name: "Placester",
    hub: "proptech",
    careersUrl: "https://placester.com/careers",
    website: "https://placester.com",
    state: "Massachusetts",
    segment: "Real Estate Agent Website Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "robin",
    name: "Robin",
    hub: "proptech",
    careersUrl: "https://www.robinpowered.com/careers",
    website: "https://www.robinpowered.com",
    state: "Massachusetts",
    segment: "Workplace Experience Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "getcovered",
    name: "GetCovered",
    hub: "proptech",
    careersUrl: "https://getcovered.io/careers",
    website: "https://getcovered.io",
    state: "Colorado",
    segment: "Renters Insurance / PropTech-Insurtech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "turbotenant",
    name: "TurboTenant",
    hub: "proptech",
    careersUrl: "https://www.turbotenant.com/careers",
    website: "https://www.turbotenant.com",
    state: "Colorado",
    segment: "Landlord/DIY Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "homebot",
    name: "Homebot",
    hub: "proptech",
    careersUrl: "https://www.homebot.ai/careers",
    website: "https://www.homebot.ai",
    state: "Colorado",
    segment: "Homeowner Engagement Platform",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "digible",
    name: "Digible",
    hub: "proptech",
    careersUrl: "https://www.digible.com/careers",
    website: "https://www.digible.com",
    state: "Colorado",
    segment: "Multifamily Marketing Agency/Tech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "netvendor",
    name: "NetVendor",
    hub: "proptech",
    careersUrl: "https://www.netvendor.com/careers",
    website: "https://www.netvendor.com",
    state: "Georgia",
    segment: "Vendor Compliance & Insurance Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "smartrent",
    name: "SmartRent",
    hub: "proptech",
    careersUrl: "https://smartrent.com/careers",
    website: "https://smartrent.com",
    state: "Arizona",
    segment: "Smart Home / Multifamily IoT",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "offerpad",
    name: "Offerpad",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.offerpad.com/careers",
    website: "https://www.offerpad.com",
    state: "Arizona",
    segment: "iBuying / Real Estate Transactions",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "opendoor",
    name: "Opendoor",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.opendoor.com/careers",
    website: "https://www.opendoor.com",
    state: "Arizona",
    segment: "iBuying / Real Estate Transactions",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "pointcentral",
    name: "PointCentral",
    hub: "proptech",
    careersUrl: "https://www.pointcentral.com/careers",
    website: "https://www.pointcentral.com",
    state: "Arizona",
    segment: "Smart Home for SFR (Alarm.com subsidiary)",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "entrata",
    name: "Entrata",
    hub: "proptech",
    careersUrl: "https://www.entrata.com/careers",
    website: "https://www.entrata.com",
    state: "Utah",
    segment: "Property Management Software (AI leasing/payments)",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "rentec-direct",
    name: "Rentec Direct",
    hub: "proptech",
    careersUrl: "https://www.rentecdirect.com/careers",
    website: "https://www.rentecdirect.com",
    state: "Oregon",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "second-nature",
    name: "Second Nature",
    hub: "proptech",
    careersUrl: "https://www.secondnature.com/careers",
    website: "https://www.secondnature.com",
    state: "Tennessee",
    segment: "Resident Benefits / Property Management SaaS",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "home365",
    name: "Home365",
    hub: "opco",
    careersUrl: "https://www.home365.co/careers",
    website: "https://www.home365.co",
    state: "Nevada",
    segment: "SFR Full-Service Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "cecilian-partners",
    name: "Cecilian Partners",
    hub: "proptech",
    careersUrl: "https://www.cecilianpartners.com/careers",
    website: "https://www.cecilianpartners.com",
    state: "Pennsylvania",
    segment: "New Home Community Development Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "costar-group",
    name: "CoStar Group",
    hub: "proptech",
    careersUrl: "https://www.costargroup.com/careers",
    website: "https://www.costargroup.com",
    state: "Virginia",
    segment: "Real Estate Data & Analytics",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "alarmcom",
    name: "Alarm.com",
    hub: "proptech",
    careersUrl: "https://www.alarm.com/careers",
    website: "https://www.alarm.com",
    state: "Virginia",
    segment: "Smart Property / Security Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "notarize-proof",
    name: "Notarize (Proof)",
    hub: "proptech",
    careersUrl: "https://www.proof.com/careers",
    website: "https://www.proof.com",
    state: "Virginia",
    segment: "Remote Online Notarization for Real Estate Closings",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "zillow-group",
    name: "Zillow Group",
    hub: "proptech",
    careersUrl: "https://www.zillow.com/careers",
    website: "https://www.zillow.com",
    state: "Washington",
    segment: "Real Estate Marketplace",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "redfin",
    name: "Redfin",
    hub: "proptech",   // REVIEW: opco/proptech call is arguable
    careersUrl: "https://www.redfin.com/careers",
    website: "https://www.redfin.com",
    state: "Washington",
    segment: "Real Estate Brokerage Tech",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "knock-crm",
    name: "Knock CRM",
    hub: "proptech",
    careersUrl: "https://www.knockrentals.com/careers",
    website: "https://www.knockrentals.com",
    state: "Washington",
    segment: "Multifamily Leasing CRM",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "rocket-companies",
    name: "Rocket Companies",
    hub: "proptech",
    careersUrl: "https://www.rocketcompanies.com/careers",
    website: "https://www.rocketcompanies.com",
    state: "Michigan",
    segment: "Mortgage / Real Estate Fintech",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "rent-manager-lcs",
    name: "Rent Manager (LCS)",
    hub: "proptech",
    careersUrl: "https://www.rentmanager.com/careers",
    website: "https://www.rentmanager.com",
    state: "Ohio",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "mri-software",
    name: "MRI Software",
    hub: "proptech",
    careersUrl: "https://www.mrisoftware.com/careers",
    website: "https://www.mrisoftware.com",
    state: "Ohio",
    segment: "Real Estate/Property Management Software",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "density",
    name: "Density",
    hub: "proptech",
    careersUrl: "https://www.density.io/careers",
    website: "https://www.density.io",
    state: "Ohio",
    segment: "Occupancy Sensing for Buildings",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "bright-mls",
    name: "Bright MLS",
    hub: "proptech",
    careersUrl: "https://www.brightmls.com/careers",
    website: "https://www.brightmls.com",
    state: "Maryland",
    segment: "Real Estate MLS / Listings Data Technology",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "renters-warehouse",
    name: "Renters Warehouse",
    hub: "opco",
    careersUrl: "https://www.renterswarehouse.com/careers",
    website: "https://www.renterswarehouse.com",
    state: "Minnesota",
    segment: "SFR Property Management Franchise",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "doorloop",
    name: "DoorLoop",
    hub: "proptech",
    careersUrl: "https://www.doorloop.com/careers",
    website: "https://www.doorloop.com",
    state: "Florida",
    segment: "Property Management Software",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "envoy",
    name: "Envoy",
    hub: "proptech",
    careersUrl: "https://envoy.com/careers",
    website: "https://envoy.com",
    state: "California",
    segment: "Workplace Experience Platform",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "leaselock",
    name: "LeaseLock",
    hub: "proptech",
    careersUrl: "https://www.leaselock.com/careers",
    website: "https://www.leaselock.com",
    state: "California",
    segment: "Deposit-Free Leasing Insurtech",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "doorstead",
    name: "Doorstead",
    hub: "opco",
    careersUrl: "https://www.doorstead.com/careers",
    website: "https://www.doorstead.com",
    state: "California",
    segment: "Guaranteed-Rent Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "belong",
    name: "Belong",
    hub: "opco",
    careersUrl: "https://belonghome.com/careers",
    website: "https://belonghome.com",
    state: "California",
    segment: "SFR Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "medical-properties-trust",
    name: "Medical Properties Trust",
    hub: "opco",
    careersUrl: "https://www.medicalpropertiestrust.com/careers",
    website: "https://www.medicalpropertiestrust.com",
    state: "Alabama",
    segment: "Healthcare REIT",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "uniti-group",
    name: "Uniti Group",
    hub: "opco",
    careersUrl: "https://www.uniti.com/careers",
    website: "https://www.uniti.com",
    state: "Arkansas",
    segment: "Infrastructure REIT (fiber/real estate)",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "starwood-property-trust",
    name: "Starwood Property Trust",
    hub: "opco",
    careersUrl: "https://www.starwoodcapital.com/careers",
    website: "https://www.starwoodpropertytrust.com",
    state: "Connecticut",
    segment: "Commercial Mortgage REIT",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "alexander-and-baldwin",
    name: "Alexander & Baldwin",
    hub: "opco",
    careersUrl: "https://www.alexanderbaldwin.com/careers",
    website: "https://www.alexanderbaldwin.com",
    state: "Hawaii",
    segment: "Commercial Real Estate / Land REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "kite-realty-group-trust",
    name: "Kite Realty Group Trust",
    hub: "opco",
    careersUrl: "https://www.kiterealty.com/careers",
    website: "https://www.kiterealty.com",
    state: "Indiana",
    segment: "Shopping Center REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "lamar-advertising-company",
    name: "Lamar Advertising Company",
    hub: "opco",
    careersUrl: "https://www.lamar.com/careers",
    website: "https://www.lamar.com",
    state: "Louisiana",
    segment: "Outdoor Advertising REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "eastgroup-properties",
    name: "EastGroup Properties",
    hub: "opco",
    careersUrl: "https://www.eastgroup.net/careers",
    website: "https://www.eastgroup.net",
    state: "Mississippi",
    segment: "Industrial REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "epr-properties",
    name: "EPR Properties",
    hub: "opco",
    careersUrl: "https://www.eprkc.com/careers",
    website: "https://www.eprkc.com",
    state: "Missouri",
    segment: "Experiential/Entertainment REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "veris-residential",
    name: "Veris Residential",
    hub: "opco",
    careersUrl: "https://www.verisresidential.com/careers",
    website: "https://www.verisresidential.com",
    state: "New Jersey",
    segment: "Multifamily REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "highwoods-properties",
    name: "Highwoods Properties",
    hub: "opco",
    careersUrl: "https://www.highwoods.com/careers",
    website: "https://www.highwoods.com",
    state: "North Carolina",
    segment: "Office REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "greystar",
    name: "Greystar",
    hub: "proptech",
    careersUrl: "https://www.greystar.com/careers",
    website: "https://www.greystar.com",
    state: "South Carolina",
    segment: "World's Largest Multifamily Property Manager",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "easterly-government-properties",
    name: "Easterly Government Properties",
    hub: "opco",
    careersUrl: "https://www.easterlyre.com/careers",
    website: "https://www.easterlyre.com",
    state: "District of Columbia",
    segment: "Government-Leased Office REIT",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "cohen-esrey-communities",
    name: "Cohen-Esrey Communities",
    hub: "opco",
    careersUrl: "https://www.cohenesrey.com/careers",
    website: "https://www.cohenesrey.com",
    state: "Kansas",
    segment: "Multifamily Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "case-and-associates",
    name: "Case & Associates",
    hub: "opco",
    careersUrl: "https://www.caseandassociates.com/careers",
    website: "https://www.caseandassociates.com",
    state: "Oklahoma",
    segment: "Multifamily Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "oakbrook-corporation",
    name: "Oakbrook Corporation",
    hub: "opco",
    careersUrl: "https://www.oakbrookcorp.com/careers",
    website: "https://www.oakbrookcorp.com",
    state: "Wisconsin",
    segment: "Commercial & Residential Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "bh-management-services",
    name: "BH Management Services",
    hub: "opco",
    careersUrl: "https://www.bhmanagement.com/careers",
    website: "https://www.bhmanagement.com",
    state: "Iowa",
    segment: "Multifamily Property Management",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "atria-senior-living",
    name: "Atria Senior Living",
    hub: "opco",
    careersUrl: "https://www.atriaseniorliving.com/careers",
    website: "https://www.atriaseniorliving.com",
    state: "Kentucky",
    segment: "Senior Living Property Management",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "picerne-real-estate-group",
    name: "Picerne Real Estate Group",
    hub: "opco",
    careersUrl: "https://www.picerne.com/careers",
    website: "https://www.picerne.com",
    state: "Rhode Island",
    segment: "Multifamily & Military Housing Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "the-lund-company",
    name: "The Lund Company",
    hub: "opco",
    careersUrl: "https://www.lundco.com/careers",
    website: "https://www.lundco.com",
    state: "Nebraska",
    segment: "Multifamily & Commercial Property Management",
    verified: true,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "tamarack-property-management",
    name: "Tamarack Property Management",
    hub: "proptech",
    careersUrl: "https://www.tamarackproperty.com/careers",
    website: "https://www.tamarackproperty.com",
    state: "Montana",
    segment: "Affordable/Multifamily/Senior Housing Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "mountain-property-management",
    name: "Mountain Property Management",
    hub: "opco",
    careersUrl: "https://jacksonholeproperties.net/careers",
    website: "https://jacksonholeproperties.net",
    state: "Wyoming",
    segment: "Residential & HOA Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
  {
    id: "redstone",
    name: "Redstone",
    hub: "opco",
    careersUrl: "https://www.redstonevt.com/careers",
    website: "https://www.redstonevt.com",
    state: "Vermont",
    segment: "Multifamily & Commercial Property Management",
    verified: false,
    method: null,   // greenhouse | lever | workday | dom
    atsSlug: null,
    active: true,
  },
];

/** Only companies run.js can actually scrape right now. */
export const scrapeable = (hub) => COMPANIES.filter(c =>
  c.active && c.method && (!hub || c.hub === hub));

/** Configured but not yet resolvable — surface these, do not hide them. */
export const pending = () => COMPANIES.filter(c => c.active && !c.method);

export default COMPANIES;
